# This file is generated by the release workflow from packaging/homebrew/veld.rb.tmpl.
# Do not edit it directly in the homebrew-tap repo — edit the template and re-release.
class Veld < Formula
  desc "Zero-trust mesh VPN daemon and CLI"
  homepage "https://veld.io"
  license "MIT"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/veldmesh/veld/releases/download/v#{version}/veld-v#{version}-darwin_arm64.tar.gz"
      sha256 "4d645fbdbff78eafb505229a6fee2731fd59c00b811b6e8446a88ee42d161450"
    else
      url "https://github.com/veldmesh/veld/releases/download/v#{version}/veld-v#{version}-darwin_amd64.tar.gz"
      sha256 "977608133310773dc7e073ff7a1b72ae8684c7a89d6712b1cf58900adc47b5c7"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/veldmesh/veld/releases/download/v#{version}/veld-v#{version}-linux_arm64.tar.gz"
      sha256 "5aeb562df77cbce7c288e45cbcd1839de46b00b143e954f90916e3d012a215b2"
    else
      url "https://github.com/veldmesh/veld/releases/download/v#{version}/veld-v#{version}-linux_amd64.tar.gz"
      sha256 "b494b9dd35bd81477c4e9151efe538da9007206ddbf69f3184562c9a57a104e9"
    end
  end

  def install
    bin.install "veld"
    bin.install "veld-daemon"
    bin.install "veld-coord"
  end

  service do
    run [opt_bin/"veld-daemon", "--config", etc/"veld/config.toml"]
    keep_alive true
    log_path   var/"log/veld-daemon.log"
    error_log_path var/"log/veld-daemon.log"
  end

  test do
    assert_equal "v#{version}", shell_output("#{bin}/veld version").strip
  end
end
